### ISSUE TITLE
[Bug] Lỗi khi không cấp quyền truy cập camera/photo gallery iOS

### ISSUE THREAD

**Issue by deathemperor** [papaya-insurtech/mango-bug-report#1]
- Không cấp quyền truy cập gallery: nhấn chọn hình từ thư viện báo "có lỗi xảy ra"
- Không cấp quyền truy cập camera: nhấp chụp hình hiện ra loading không dừng

Chưa kiểm tra nhưng gần như cũng sẽ bị ở Android.

**Comment by a8thunder** [comment]
DONE.
