### ISSUE TITLE
UAT/Heathcare/ Một số tính năng cần thêm

### ISSUE THREAD

**Issue by ToantranPPY** [papaya-insurtech/mango-bug-report#100]
- [x] Cần thể hiện phần hoa hồng
- [x] Cho phép thay đổi sang tình trạng complete/ Decline
- [x] Cần thể hiện phí theo từng quyền lợi
- [x] Có chức năng upload giấy chứng nhận bảo hiểm
- [x] Cho phép add mã giấy chứng nhận
- [x] Cho phép extract mẫu giấy yêu cầu theo từng đơn hàng với đầy đủ thông tin để gửi CTBH

**Comment by deathemperor** [comment]
issue liên quan: https://github.com/papaya-insurtech/mango-bug-report/issues/77

**Comment by ToantranPPY** [comment]
Noted

**Comment by deathemperor** [comment]
@ToantranPPY GCN upload 1 file hay nhiều file anh?

**Comment by ToantranPPY** [comment]
@deathemperor cho phép upload nhiều file nhé, tks Lộc

**Comment by deathemperor** [comment]
done UAT

**Comment by ToantranPPY** [comment]
hi @deathemperor chưa có "Decline" button

**Comment by LocPham0311** [comment]
done decline button

**Comment by ToantranPPY** [comment]
done
