### ISSUE TITLE
Prod/ Check thông tin CTV trên file hoa hồng - DH 843463

### ISSUE THREAD

**Issue by ToantranPPY** [papaya-insurtech/mango-bug-report#103]
DH 843463
thông tin CTV trên portal thể hiện là 193799 - Trương Chí Hiếu. Tuy nhiên file comm thể hiện là 012345 - Nguyễn Thy Thuỷ Tiên
https://portal.pro.papaya.asia/portal/tnds-car/7e3cbeac-a37a-4daa-be7f-fddb0b84c68a

**Comment by LocPham0311** [comment]
anh Toàn cho em list các order_code bị sai với

**Comment by ToantranPPY** [comment]
gửi Lộc @LocPham0311 
322580
472292
502131
543436
569420

**Comment by LocPham0311** [comment]
Anh @ToantranPPY check giúp em cái đơn ở trên nhé với anh check giúp em 3 đơn này hoa hồng đúng chưa luôn nhé (đây là 3 đơn đã status: complete mà chưa có hoa hồng)
748865
896827
692503

**Comment by ToantranPPY** [comment]
@LocPham0311 check giúp hoa hồng VCX của DH 692503 chưa đúng (dư 119,527 d)

**Comment by LocPham0311** [comment]
anh check lai nhe
