### ISSUE TITLE
Portal / Hiển thị thông tin nghề nghiệp cua CTV

### ISSUE THREAD

**Issue by duonglna** [papaya-insurtech/mango-bug-report#104]
Hiển thị thông tin nghề nghiệp đã nhập khi đăng ký của CTV trên Portal

**Comment by deathemperor** [comment]
@duonglna Portal đã hiện nghề nghiệp nha
![Screen Shot 2022-01-04 at 11 01 53 AM](https://user-images.githubusercontent.com/4255482/148008039-35617bf5-5644-46e4-9c03-4e6f78567e50.png)

**Comment by duonglna** [comment]
Ok anh, em thấy rồi ạ
