### ISSUE TITLE
Là Ops, tôi muốn đơn hàng thanh toán không bị trùng cả kể deposit & thanh toán thẻ

### ISSUE THREAD

**Issue by ToantranPPY** [papaya-insurtech/mango-bug-report#105]
Là Ops, tôi muốn đơn hàng thanh toán không bị trùng cả kể deposit & thanh toán thẻ: Hệ thống chỉ cho phép thanh toán thành công (duy nhất 01 lần)

**Comment by deathemperor** [comment]
trên production đã xóa được deposit code khi đơn thanh toán thành công, anh có thể kiểm tra với đơn hàng mới nhất https://portal.pro.papaya.asia/portal/preorder-motorbike/505

Chai payment link thì đã báo Chai và nó nói sẽ support, chưa biết khi nào có. khi nào nó cung cấp thì em sẽ apply.

**Comment by ToantranPPY** [comment]
noted with thank @deathemperor

**Comment by ToantranPPY** [comment]
okay, done
