### ISSUE TITLE
Thứ tự của các đơn hàng trong phần giao dịch

### ISSUE THREAD

**Issue by duonglna** [papaya-insurtech/mango-bug-report#106]
Problem: hiện nay đơn hàng trong phần Giao dịch, ví dụ TNDS Ô tô đang theo thứ tự làm user khó quản lý, theo dõi 
Suggestion: sắp xếp theo ngày cập nhật trạng thái đơn hàng từ mới nhất đến cũ

**Comment by a8thunder** [comment]
DONE!
