### ISSUE TITLE
PROD/ số tiền hoa hồng của đơn hàng 972272 để hiện không đúng

### ISSUE THREAD

**Issue by ToantranPPY** [papaya-insurtech/mango-bug-report#109]
PROD/ số tiền hoa hồng của đơn hàng 972272 để hiện không đúng

Số đúng là 1.326.240 đồng
![image](https://user-images.githubusercontent.com/94037218/150270427-aca1bde6-ccae-4838-af64-ff13c2c4eb1d.png)

**Comment by deathemperor** [comment]
em đề nghị giải quyết vấn đề này chung với việc revamp tab hoa hồng lại 1 thể luôn.
