### ISSUE TITLE
PTI - Không ghi nhận quyền lợi tai nạn + Không có GCN

### ISSUE THREAD

**Issue by ToantranPPY** [papaya-insurtech/mango-bug-report#11]
UAT- DH http://papaya-mango-portal-uat.s3-website-ap-southeast-1.amazonaws.com/portal/preorder-motorbike/100121
- Không ghi nhận quyền lợi tai nạn
- Không có giấy chứng nhận
![image](https://user-images.githubusercontent.com/94037218/141941743-d1ee5079-531c-4f42-b695-5c12a0562d0c.png)

**Comment by deathemperor** [comment]
@ToantranPPY Fixed
