### ISSUE TITLE
PROD/ Thẻ Hợp đồng TNDS: thiếu thông tin địa chỉ nhận giấy chứng nhận BH

### ISSUE THREAD

**Issue by ToantranPPY** [papaya-insurtech/mango-bug-report#110]
PROD/ Thẻ Hợp đồng TNDS: thiếu thông tin địa chỉ nhận giấy chứng nhận BH
![image](https://user-images.githubusercontent.com/94037218/150271228-461a22aa-f8a4-48c0-a32e-51b65fb9502d.png)

**Comment by deathemperor** [comment]
fixed

**Comment by ToantranPPY** [comment]
@deathemperor check lại giúp anh:
UAT/PROD đều chưa thấy thông tin địa chỉ nhận GCNBH
![image](https://user-images.githubusercontent.com/94037218/150527656-1a750641-8d9f-4116-9098-fd9590bb4da4.png)

![image](https://user-images.githubusercontent.com/94037218/150527728-f7e5b6d5-ebe6-455f-b653-61f2affec895.png)

**Comment by deathemperor** [comment]
Check lại. em thêm địa chỉ nhận GCN vào mục "Hợp Đồng"

**Comment by ToantranPPY** [comment]
UAT okay, nhờ Lộc deloy trên Prod giúp nhé
Cảm ơn Lộc

**Comment by ToantranPPY** [comment]
@deathemperor , Lộc deloy trên prod nhé

**Comment by deathemperor** [comment]
em đưa lên prod rồi nhe anh @ToantranPPY
