### ISSUE TITLE
UAT-BulkXM-Mobile-26Jan22

### ISSUE THREAD

**Issue by nhinguyenpapaya** [papaya-insurtech/mango-bug-report#111]
Mua phiếu
- [x] Giá chiết khấu theo số lượng bị ngược thứ tự
- [x] Cho nhập số lượng phiếu muốn mua
- [x] Giá (màu đỏ) thay đổi theo số lượng mua
- [x] Font chữ list giá chiết khấu khác
- [x] Chưa có screen khi có đơn bulk chưa thanh toán
![1643173430407](https://user-images.githubusercontent.com/96039997/151107026-0969acd2-8616-4033-b563-024f1f8e7a1b.jpg)
![BHXM Bulk_Kích hoạt](https://user-images.githubusercontent.com/96039997/151107061-2576b730-2691-43c0-a101-668ce722329a.png)

Hoàn phiếu
- [x] Tăng touch target cho Trả lại phiếu trong kho
![1643173430387](https://user-images.githubusercontent.com/96039997/151107088-09ad6815-863a-4e00-adfa-f48e954c0b53.jpg)
- [x] Nút hoàn phiếu bị lệch
![1643173430399](https://user-images.githubusercontent.com/96039997/151107153-5e0ed915-dc02-40bb-af3d-39753f7d56fa.jpg)
- [x] #112
https://user-images.githubusercontent.com/96039997/151107175-8f559084-45d4-4629-8fa0-5b4956b1625e.mp4
https://user-images.githubusercontent.com/96039997/151107189-2434e5eb-d6ca-44e2-b362-408c9b4d8540.mp4

Phiếu đã bán
- [x] Status của phiếu: Chờ thanh toán -> Chưa kích hoạt
- [x] Thu gọn khoảng cách
![1643173430415](https://user-images.githubusercontent.com/96039997/151107243-9cda93d6-9676-42a1-8dc2-380e556b4379.jpg)

**Comment by nhinguyenpapaya** [comment]
- [ ] Thêm UI giải thích cách tính tiền hoàn trả
![BHXM Bulk_Hoàn phiếu](https://user-images.githubusercontent.com/96039997/151117550-3d6153e7-80a2-426c-9ee3-7c0b59031090.png)

**Comment by a8thunder** [comment]
DONE!
