### ISSUE TITLE
Loading indicator có độ delay khoảng 1s

### ISSUE THREAD

**Issue by deathemperor** [papaya-insurtech/mango-bug-report#113]
https://user-images.githubusercontent.com/4255482/151319926-f753907e-21e0-459e-a906-f8977e21d2c2.MOV

**Comment by a8thunder** [comment]
Hiện tại chỗ này em đang để delay 1.2s sau lần touch cuối cùng mới gọi server, để tránh gọi xuống server nhiều lần, anh thấy 0 cần thiết thì em có thể xoá chỗ này @deathemperor

**Comment by deathemperor** [comment]
cách làm đó ảnh hưởng UX. em cần apply debounce hơn là delay.

**Comment by a8thunder** [comment]
DONE!
