### ISSUE TITLE
Giá mặc định của bulk là 66k và 86k

### ISSUE THREAD

**Issue by deathemperor** [papaya-insurtech/mango-bug-report#114]
2 giá này đâu bao giờ có. Nên dùng giá mặc định theo 1 đơn vị (UI của Nhi để là vậy)

![image](https://user-images.githubusercontent.com/4255482/151335491-ed5877c7-234b-4a98-ab24-ac436a2f4b5c.png)

**Comment by a8thunder** [comment]
@deathemperor nhi báo muốn giá nhảy theo như trong cái list hiển thị giá bên dưới khi chọn số lượng anh

**Comment by deathemperor** [comment]
@a8thunder ừa nhảy theo vậy đúng rồi nhưng mà mới vào lại báo giá 66k/86k, 2 giá này đâu bao giờ có.

**Comment by a8thunder** [comment]
DONE!
