### ISSUE TITLE
Bulk/ Số tiền thanh toán thể hie

### ISSUE THREAD

**Issue by ToantranPPY** [papaya-insurtech/mango-bug-report#117]
Bulk/ Số tiền thanh toán thể hiện sai
![Screenshot_20220128-132033](https://user-images.githubusercontent.com/94037218/151498017-afe4cbaa-f895-45ed-93a5-05a88a2cb76d.png)

**Comment by LocPham0311** [comment]
@deathemperor https://github.com/papaya-insurtech/mango-serverless/pull/100 anh review xong deploy giup em nhe

**Comment by ToantranPPY** [comment]
done
