### ISSUE TITLE
Số tiền trên giao dịch hoàn trả hiển thị là "Phí HĐ", nên đổi thành "số tiền hoàn trả"

### ISSUE THREAD

**Issue by deathemperor** [papaya-insurtech/mango-bug-report#128]
cc @nhinguyenpapaya 

![image](https://user-images.githubusercontent.com/4255482/155053636-d2a61520-b8b5-4a43-829b-b08a5ca8a9bf.png)

**Comment by a8thunder** [comment]
DONE!
