### ISSUE TITLE
Nội dung email layout hiển thị xấu

### ISSUE THREAD

**Issue by deathemperor** [papaya-insurtech/mango-bug-report#133]
1. padding trái/phải sát rìa quá
2. 36.300 đồng x 1 phiếu bị xuống hàng
3. 3 tấm hình hướng dẫn bị mờ

![img](https://user-images.githubusercontent.com/4255482/155117486-24f42c5d-9ca9-407b-9707-d40a8e536ee7.png)

**Comment by LocPham0311** [comment]
theo design là 36.300 đồng với x1 phiếu là 2 dòng đó anh

**Comment by LocPham0311** [comment]
@nhinguyenpapaya chị gửi cho e 3 cái hình chất lượng cao xíu nhé
