### ISSUE TITLE
UAT/nội dung email thông báo đóng phí và xác nhận đóng phí của AAA - TNDS xe oto

### ISSUE THREAD

**Issue by ToantranPPY** [papaya-insurtech/mango-bug-report#138]
UAT/nội dung email thông báo đóng phí và xác nhận đóng phí của AAA - TNDS xe oto

hi Lộc & Nhi,
những email thông báo đóng phí/ xác nhận đóng phí TNDS xe oto của AAA chưa thể hiện lưu ý:
![image](https://user-images.githubusercontent.com/94037218/156690331-8d64b9f3-43e1-4ada-8944-9f0b46079330.png)

**Comment by deathemperor** [comment]
em đã thay đổi rồi nhe

**Comment by ToantranPPY** [comment]
done
