### ISSUE TITLE
UAT: TNDS - chỉ cần thể hiện phí ở mục " Phí bảo hiểm" _ không cần thể hiện phí phần từng Công ty bảo hiểm

### ISSUE THREAD

**Issue by ToantranPPY** [papaya-insurtech/mango-bug-report#14]
UAT: TNDS - chỉ cần thể hiện phí ở mục " Phí bảo hiểm" _ không cần thể hiện phí phần từng Công ty bảo hiểm
![image](https://user-images.githubusercontent.com/94037218/141945586-a9371625-8ecb-4f02-a01f-bc370b4d8c24.png)

**Comment by deathemperor** [comment]
chỗ này anh update từ UI trước rồi tech sẽ apply theo nhe anh @ToantranPPY

**Comment by deathemperor** [comment]
@a8thunder UI có rồi trên figma, em apply nhé

**Comment by a8thunder** [comment]
DONE!

**Comment by ToantranPPY** [comment]
okay, done 
![Screenshot_20211202-144744](https://user-images.githubusercontent.com/94037218/144379874-bb8dcdb3-292b-4fe6-9ed1-dbc675f76605.png)

**Comment by deathemperor** [comment]
@a8thunder phần phí bảo hiểm bị lỗi hiển thị 0 đồng, khi chọn cty BH mới ra gia

Đúng: lúc nào cũng hiển thị giá dù chưa chọn cty, vì giá của tất cả cty đều bằng nhau.

**Comment by a8thunder** [comment]
@deathemperor  mới vô em sẽ auto select bảo hiểm đầu tiên luôn anh hỉ. Để lấy cái giá ban đầu show ra

**Comment by deathemperor** [comment]
@a8thunder  OK confirmed.

**Comment by a8thunder** [comment]
DONE!

**Comment by ToantranPPY** [comment]
okay, done,
Pls build next version on prod
