### ISSUE TITLE
xe mới - bảng chào phí hiển thị sai năm sản xuất

### ISSUE THREAD

**Issue by ToQuyenPPY** [papaya-insurtech/mango-bug-report#142]
mã đơn hàng: 349062 
chọn năm sản xuất 2022 -> báo phí hiển thị 2020
![image](https://user-images.githubusercontent.com/95274936/156962241-3dc74855-444d-4a6f-a2d2-23d334909231.png)
![image](https://user-images.githubusercontent.com/95274936/156962250-ffa6cc79-49f1-40c0-b776-d3903a6208fb.png)

**Comment by deathemperor** [comment]
@a8thunder chỗ này anh support thêm 1 param `year` cho API `generate_pdf_quotation`, nếu xe mới thì em input thêm số năm đã chọn vào param `year`. như vậy thì khi tạo ra file báo giá sẽ đúng số năm

**Comment by ToantranPPY** [comment]
@ToQuyenPPY check lại issue này đã được fix và deploy trên prod chưa nhé

**Comment by ToQuyenPPY** [comment]
@ToantranPPY  em check trên prod đã fix ạ
