### ISSUE TITLE
Thay đổi UX chọn tỉnh thành quận phường

### ISSUE THREAD

**Issue by deathemperor** [papaya-insurtech/mango-bug-report#146]
https://user-images.githubusercontent.com/4255482/157167131-032aeb3f-794c-4c27-b289-c72e5f248644.MOV

UX chọn tỉnh thành quận phường của Lazada rất dễ dùng, chọn rất nhanh. Cần apply tương tự cho tất cả các chỗ địa chỉ của mình. Vẫn hiện thị 3 fields như hiện tại nhưng khi touch vào tỉnh thành thì làm như Lazada, khi touch chọn quận/phường thì vẫn giữ như cũ.

Cc @nhinguyenpapaya @ToantranPPY

**Comment by a8thunder** [comment]
DONE!
