### ISSUE TITLE
Cho phép copy số tài khoản và số tiền

### ISSUE THREAD

**Issue by deathemperor** [papaya-insurtech/mango-bug-report#149]
Thêm icon copy vào 2 thông tin như hình vẽ, touch vào sẽ copy số tài khoản và số tiền.

![image](https://user-images.githubusercontent.com/4255482/157372243-b387b33c-9697-4953-928b-8ab5e46ea047.png)

**Comment by a8thunder** [comment]
DONE!

**Comment by deathemperor** [comment]
apply feature này cho tất cả những screen thể hiện thông tin thanh toán luôn @a8thunder

**Comment by a8thunder** [comment]
@deathemperor em apply hết các màn hình hiển thị payment luôn rồi anh
