### ISSUE TITLE
P-203: Là Op Admin, tôi muốn export data của thẻ “Đơn sỉ” trên portal và thay đổi một số thông tin thể hiện

### ISSUE THREAD

**Issue by ToantranPPY** [papaya-insurtech/mango-bug-report#151]
- Remove column: Công ty BH
- Add phương thức thanh toán: VNPT-epay; Chai-pay; Non_cash
- Cho phép export ra file excel gồm các thông tin:
  + Mã đơn hàng
  + Sản phẩm: TNDS / TNDS + TN
  + Số phiếu phiếu mua
  + Số phiếu còn lại
  + Số phiếu hoàn trả
  + Số tiền thanh toán (của đơn hàng)
  + Trạng thái (của đơn hàng)
  + Ngày tạo (Created at)
  + Ngày thanh toán (Paid at)
  + Mã số CTV
  + Tên CTV
  + Mã CTV level 1
  + Tên CTV level 1
  + Group type (coming soon)
  + Group name (coming soon)

**Comment by deathemperor** [comment]
em đã deploy UAT

**Comment by ToantranPPY** [comment]
UAT okay, deploy prod giúp anh, cảm ơn Lộc
