### ISSUE TITLE
PJICO: không view được giấy chứng nhận của PJICO trên portal

### ISSUE THREAD

**Issue by ToantranPPY** [papaya-insurtech/mango-bug-report#153]
http://papaya-mango-portal-uat.s3-website-ap-southeast-1.amazonaws.com/portal/preorder-motorbike/100538
![image](https://user-images.githubusercontent.com/94037218/158120053-544a8352-a5ee-4c29-a368-1cf97acbdfc5.png)

**Comment by deathemperor** [comment]
do link GCN của PJICO mình không download được nên phải xem = trang của họ. trang này đang bị lỗi.

**Comment by deathemperor** [comment]
em check lại thì PJICO đã fix trên sandbox của họ rồi

**Comment by ToantranPPY** [comment]
Done
