### ISSUE TITLE
UAT - No connection - 15Mar22

### ISSUE THREAD

**Issue by nhinguyenpapaya** [papaya-insurtech/mango-bug-report#154]
- [x] Đổi tất cả message: Error During Communication -> Có lỗi xảy ra
![1647329013095](https://user-images.githubusercontent.com/96039997/158330141-92f29b1b-4cb2-41a6-a498-995b7930306e.jpg)

- [x] Chưa có thông báo mất kết nối trong bulk xe máy và bảo hiểm sức khoẻ
![1647329013089](https://user-images.githubusercontent.com/96039997/158330256-aae7c376-503a-4e6c-9abf-1a75172acd88.jpg)
![1647329013076](https://user-images.githubusercontent.com/96039997/158330264-6fb8b619-647c-43c8-bf59-10969202639a.jpg)
![1647329013069](https://user-images.githubusercontent.com/96039997/158330266-e49317a8-e80d-4499-a719-7fe6da28a085.jpg)

- [x] Không qua trang tiếp theo nếu không có mạng

**Comment by a8thunder** [comment]
DONE!
