### ISSUE TITLE
UAT/ Portal/ Loại hình kinh doanh: add thêm 

### ISSUE THREAD

**Issue by ToantranPPY** [papaya-insurtech/mango-bug-report#155]
UAT/ Portal/ Loại hình kinh doanh: add thêm:
- Tiệm tạp hóa
- Master Life
- Super Agent
- Telesales

**Comment by deathemperor** [comment]
done

**Comment by ToantranPPY** [comment]
UAT okay, pls deploy prod env giúp anh, tks Lộc
