### ISSUE TITLE
TNDS xe tải - không nhập được số tấn lẻ (1.4 tấn) -> nếu nhập số tấn tròn 1 hoặc 2 -> giấy CN hiển thị sai thông tin

### ISSUE THREAD

**Issue by ToQuyenPPY** [papaya-insurtech/mango-bug-report#156]
![image](https://user-images.githubusercontent.com/95274936/158514298-70bfdf74-442b-4ac8-9124-64e4a744b789.png)
![image](https://user-images.githubusercontent.com/95274936/158514331-9a1909d8-7c3e-4830-8bca-05e3a103e912.png)

**Comment by deathemperor** [comment]
@ToantranPPY anh confirm giúp em request này để em đổi trên mobile app

**Comment by ToantranPPY** [comment]
@deathemperor: thống nhất trọng tải nhập theo "kg"
Cơ sở điều chỉnh: chuẩn theo giấy chứng nhận đăng kiểm

**Comment by ToantranPPY** [comment]
nhờ @a8thunder hỗ trợ nhé

**Comment by a8thunder** [comment]
Ok anh để xí em chỉnh lại theo KG @ToantranPPY

**Comment by a8thunder** [comment]
DONE!

**Comment by ToantranPPY** [comment]
@a8thunder : deloy UAT chưa em, anh check UAT vẫn chưa update

**Comment by a8thunder** [comment]
Dạ chưa anh, em đang làm số khung số máy rồi deploy luôn anh

**Comment by a8thunder** [comment]
DONE!

**Comment by ToantranPPY** [comment]
@a8thunder
- Phí bảo hiểm đang tính sai
- cần quy đổi từ kg -> tấn để áp mức phí

![image](https://user-images.githubusercontent.com/94037218/160047291-4f2ddca2-1e99-40c1-94eb-1a30f85e5101.png)
 
![image](https://user-images.githubusercontent.com/94037218/160047366-4cf05900-fd1f-46d5-ac35-29c43c3284f0.png)

**Comment by deathemperor** [comment]
đã sửa

**Comment by ToQuyenPPY** [comment]
giấy cnbh đang lỗi loại xe - PVI @deathemperor 
![image](https://user-images.githubusercontent.com/95274936/160320222-8f1a5346-25b4-43d8-a261-a3ea66aab545.png)
https://papaya-mango-car-orders-uat.s3.ap-southeast-1.amazonaws.com/tnds/2f6b0ca8-c219-4511-a399-1583accdf33e/policies/5826277a-0214-4a98-b278-843dd88566cc.pdf

**Comment by deathemperor** [comment]
anh đã fix nhe @ToQuyenPPY . thử lại giúp anh.

**Comment by ToQuyenPPY** [comment]
@deathemperor anh Lộc xem giúp em phí xe cứu thương luôn nha
![image](https://user-images.githubusercontent.com/95274936/160348689-71319c8e-2ed7-46bf-9019-711a2034ab42.png)

**Comment by ToantranPPY** [comment]
Phí bảo hiểm của xe cứu thương được tính bằng 120% phí bảo hiểm của xe vừa chở người vừa chở hàng (pickup, minivan) kinh doanh vận tải = (120% x 853.000) x 1.1 = 1.125.960 (đã có VAT)

**Comment by ToantranPPY** [comment]
@deathemperor 
Phí bảo hiểm của xe cứu thương được tính bằng 120% phí bảo hiểm của xe vừa chở người vừa chở hàng (pickup, minivan) kinh doanh vận tải = (120% x 933.000) x 1.1 = 1.231.560 (đã có VAT)

**Comment by deathemperor** [comment]
đã đưa lên production nhe anh

**Comment by ToantranPPY** [comment]
Done
