### ISSUE TITLE
P-225: Là Ops, tôi muốn validate số khung/ Số máy xe oto

### ISSUE THREAD

**Issue by ToantranPPY** [papaya-insurtech/mango-bug-report#158]
* Số khung: gồm 17 ký tự (6 ký tự cuối là dạng số)
* Số máy: tối thiểu 06 ký tự (bao gồm, chữ, số, và ký tự đặc biệt)

**Comment by a8thunder** [comment]
DONE!

**Comment by ToantranPPY** [comment]
@a8thunder: validate nhầm giữa điều kiện số khung và số máy
![image](https://user-images.githubusercontent.com/94037218/160046912-d9637e76-893a-42b8-a557-2d57453fb9f7.png)

**Comment by ToantranPPY** [comment]
@a8thunder: check lại giúp anh chưa validate số khung:
Yêu cầu: số khung: gồm 17 ký tự (6 ký tự cuối là dạng số)
Testing: nhập 07 số vẫn cho đi

**Comment by ToantranPPY** [comment]
Done
