### ISSUE TITLE
UAT Hoa hồng - 28Mar22

### ISSUE THREAD

**Issue by nhinguyenpapaya** [papaya-insurtech/mango-bug-report#161]
- [x] UI glitch
![Image from iOS (2)](https://user-images.githubusercontent.com/96039997/160329377-84ba1192-1b72-47bd-a46c-2e90615d3a53.jpg)

- [x] range ngày ở chỗ chọn tuần và ở chart hiện 2 range khác nhau
![Image from iOS](https://user-images.githubusercontent.com/96039997/160329391-b40c0b8e-b724-4258-a661-4c1ee500b06b.jpg)

- [x] thêm năm vào (ví dụ: 01/03/2021 -  07/03/2021)
![Image from iOS (1)](https://user-images.githubusercontent.com/96039997/160329443-eefd1f15-629d-4368-89f8-bef7ccf0e15e.jpg)

**Comment by a8thunder** [comment]
DONE!

**Comment by ToantranPPY** [comment]
Done
