### ISSUE TITLE
UAT: UI hoa hồng

### ISSUE THREAD

**Issue by ToantranPPY** [papaya-insurtech/mango-bug-report#162]
- Mã số chủ cây xăng: 321769
- Mã số nhân viên: 972695
 B1: Login với mã chủ cây xăng 321769
 B2: click UI hoa hồng:
  a) Thưởng hoa hồng chờ xác nhận và thanh toán: 0 => không đúng
  b) Kỳ hoa hồng không đúng với ngày trên chart
  c) Phần tích lũy và cá nhân & đội nhóm thể hiện không đúng số
  d) UI đội ngũ thể hiện phí và hoa hồng không chính xác
![UI hoa hong doi ngu](https://user-images.githubusercontent.com/94037218/160357697-7ea30565-927f-423f-9e1d-9f367b349e57.jpg)
![UI hoa hong main 2](https://user-images.githubusercontent.com/94037218/160357713-90b2e55d-028d-4bca-b703-be1158b81f88.jpg)
![UI hoa hong main](https://user-images.githubusercontent.com/94037218/160357724-4d810775-ab1a-4689-97d1-15b9b002cb01.jpg)

**Comment by a8thunder** [comment]
DONE!

**Comment by ToantranPPY** [comment]
done
