### ISSUE TITLE
PRO_ onboard Bảo Minh

### ISSUE THREAD

**Issue by ToantranPPY** [papaya-insurtech/mango-bug-report#167]
- Điều chỉnh tên BaoMinh -> Bảo Minh
- Ngày hiệu lực bảo hiểm của Bảo Minh giống rules của AAA: 
   1. Cần validate trên app giống AAA
   2. Thông báo email: có nội dung tương tự AAA

**Comment by ToantranPPY** [comment]
@a8thunder , trên app UAT Version 1.0.24 chưa validate của Bảo Minh
http://papaya-mango-portal-uat.s3-website-ap-southeast-1.amazonaws.com/portal/preorder-motorbike/100634

@QuangLoc0311 , 
- Không có ghi nhận SMS và Email báo
- Tên Bảo Minh trên app thiếu dấu

**Comment by deathemperor** [comment]
fixed

**Comment by ToantranPPY** [comment]
Done
