### ISSUE TITLE
UAT- TNDS xe may /oto: không chọn time khi app chỉnh ngày hiệu lực bảo hiểm

### ISSUE THREAD

**Issue by ToantranPPY** [papaya-insurtech/mango-bug-report#170]
Đối  với đơn hàng TNDS xe may / oto:
- Sys set Effective date = System date +1
- Users chọn CTBH: Bảo Minh hoặc AAA
- Hệ thống popup thông báo, continue
- Effective date  được auto edit = (System date +1)+ 1 days

-> Bug: Khi này users muốn điều chỉnh Time = 00:00 của Effective date trên thì không được 
-> Suggest: cho phép điều chinh time

**Comment by a8thunder** [comment]
DONE!

**Comment by ToantranPPY** [comment]
UAT done
