### ISSUE TITLE
UAT-TNDS Oto - Chưa chọn công ty BH mà đã có thông báo của công ty Bảo Minh

### ISSUE THREAD

**Issue by Nhutruong96** [papaya-insurtech/mango-bug-report#171]
UI1: Nhập thông tin xe ô tô, chủ xe
UI2: Chưa chọn công ty bảo hiểm đã xuất hiện màn hình thông báo chọn công ty bảo hiểm Bảo Minh như bên dưới 

![32843ea0e425257b7c34](https://user-images.githubusercontent.com/105489603/168257815-7ed8bccf-1974-4dd4-8327-989074d0de89.jpg)

**Comment by a8thunder** [comment]
DONE!
