### ISSUE TITLE
UAT/TNDS oto & xe máy - BIC

### ISSUE THREAD

**Issue by ToantranPPY** [papaya-insurtech/mango-bug-report#172]
1. Logo của BIC không thể hiện đúng ở mục thông tin đơn hàng
2. Thời hạn bảo hiểm của email thông báo đóng phí và email xác nhận đóng phí không đồng nhất ( dơn hàng 611647, 869958)
![d929a4eb977f56210f6e](https://user-images.githubusercontent.com/94037218/168462162-273d6b94-245f-4202-9a51-59ef175ca408.jpg)
![e31631d10245c31b9a54](https://user-images.githubusercontent.com/94037218/168462166-1c94550d-b4ed-489c-adcc-1beb0816a0ae.jpg)

**Comment by deathemperor** [comment]
@ToantranPPY cho em xin logo đúng của BIC.

@a8thunder 

Bug thời hạn bảo hiểm:

Should be: thời gian (giờ phút) mặc định là giờ hiện tại + 60p.
Right now on UAT: lấy giờ + phút hiện tại.

Production không bị.

![image](https://user-images.githubusercontent.com/4255482/168515681-0afb1a08-7617-4f4d-857f-a6f8f9cb6071.png)

**Comment by a8thunder** [comment]
DONE!

**Comment by ToantranPPY** [comment]
chưa fix hình ảnh BIC
![image](https://user-images.githubusercontent.com/94037218/169761393-c32dae02-79d7-4368-83db-e3f4c4af6aac.png)
@deathemperor

**Comment by a8thunder** [comment]
cái này để e fix anh @ToantranPPY

**Comment by a8thunder** [comment]
DONE!

**Comment by ToantranPPY** [comment]
Done
