### ISSUE TITLE
PROD- TNDS oto/ số tiền thể hiện trong email thông báo phí không đúng - mã ĐH: 163661

### ISSUE THREAD

**Issue by ToantranPPY** [papaya-insurtech/mango-bug-report#175]
- PROD- TNDS oto/ số tiền thể hiện trong email thông báo phí không đúng - mã đơn hàng: 163661
- Phí báo hiểm trước thuế trong file tính comm = 0 
![image](https://user-images.githubusercontent.com/94037218/169177694-4e2d1f3f-a8b4-41f9-9593-d0c7c460a271.png)
![image](https://user-images.githubusercontent.com/94037218/169177783-1df2cec5-bd15-4e4f-8b65-f93f6256c260.png)

**Comment by ToantranPPY** [comment]
@QuangLoc0311 , hoa hồng của đơn hàng này đang bị tính theo số phí bảo hiểm (sau thuế). 
Số đúng là phải tính theo số phí trước thuế

**Comment by QuangLoc0311** [comment]
hoa hồng trước giờ là tính theo số phí bảo hiểm sau thuế mà anh @ToantranPPY

**Comment by QuangLoc0311** [comment]
@ToantranPPY anh quên config trước thuế cho TNDS của BSH kìa

**Comment by QuangLoc0311** [comment]
anh config lại trước thuế cho TNDS của BSH xong xuất excel check lại nhé. VÌ thiếu config VAT nên số hoa hồng sẽ bị sai theo còn lỗi bên email em fix rồi nhé

**Comment by ToantranPPY** [comment]
hi @QuangLoc0311 đã config VAT cho TNDS oto BSH, file hoa hồng okay
Còn email có thể reproduce như thế nào em

**Comment by QuangLoc0311** [comment]
@ToantranPPY email anh test lại trên UAT để xem lỗi đã fix chưa nhé
