### ISSUE TITLE
UAT/ VCX - UI báo giá chỉ có Liberty

### ISSUE THREAD

**Issue by ToantranPPY** [papaya-insurtech/mango-bug-report#180]
Tại màn hình lấy báo phí chỉ có thể hiện Liberty
![UI-QL](https://user-images.githubusercontent.com/94037218/169991194-af0a24f0-81e4-4e87-b3ed-aeaa881a9b73.jpg)
![UI_bao phi](https://user-images.githubusercontent.com/94037218/169991422-dd58b060-7a04-481f-99ef-21831858095a.jpg)

**Comment by a8thunder** [comment]
DONE!

**Comment by ToantranPPY** [comment]
done

**Comment by ToantranPPY** [comment]
Done
