### ISSUE TITLE
TNDS oto: không thể hiện phí TNDS BB tại UI chọn gói BH

### ISSUE THREAD

**Issue by ToantranPPY** [papaya-insurtech/mango-bug-report#186]
TNDS oto: không thể hiện phí TNDS BB tại UI chọn gói BH
![image](https://user-images.githubusercontent.com/94037218/170905022-a76608d6-6787-46ff-9e6b-964cf4836a26.png)

@Nhutruong96 follow nhé

**Comment by a8thunder** [comment]
DONE!

**Comment by Nhutruong96** [comment]
UAT done!
