### ISSUE TITLE
PROD/ CTV ký e_signed bị báo lỗi

### ISSUE THREAD

**Issue by ToantranPPY** [papaya-insurtech/mango-bug-report#188]
PROD/ CTV ký e_signed bị báo lỗi
- Mã CTV 938291 - Số điện thoại: 0937809944
- Mã CTV 549396 - Số điện thoại: 0767131678
![image](https://user-images.githubusercontent.com/94037218/171327729-97099818-da91-4f19-bad6-fb87a3e8c130.png)

FYI: @ToQuyenPPY @Nhutruong96

**Comment by deathemperor** [comment]
fixed
