### ISSUE TITLE
UAT release 15Nov- TNDS oto - Cần gợi ý thông tin người nhận giấy chứng nhận

### ISSUE THREAD

**Issue by ToantranPPY** [papaya-insurtech/mango-bug-report#19]
TNDS oto - tại UI Hoàn thành hợp đồng: app gợi ý thông tin người nhận chứng nhận bảo hiểm từ thông tin chủ xe

**Comment by deathemperor** [comment]
remind @a8thunder

**Comment by ToantranPPY** [comment]
@deathemperor @a8thunder check giúp anh item này

**Comment by a8thunder** [comment]
DONE!

**Comment by ToantranPPY** [comment]
okay @a8thunder , @deathemperor cho deloy prod nhé, tks all
