### ISSUE TITLE
UAT Pro/Xe máy/Bảo Minh/Phí bảo hiểm thể hiện sai trên GCN

### ISSUE THREAD

**Issue by Nhutruong96** [papaya-insurtech/mango-bug-report#190]
Trên GCN : Đối với xe máy trên 50cc . Phí bảo hiểm phải thể hiện là 66.000 thay vì là 86.000

![image](https://user-images.githubusercontent.com/105489603/173515856-baccf24d-df1c-4460-ba8d-750a5ed9fc4b.png)

**Comment by deathemperor** [comment]
@Nhutruong96 anh vừa test lại UAT thì ko bị, em có thông tin đơn hàng thì `luôn` kèm theo trong các bug report giúp anh để mọi người dễ check nhe.

**Comment by deathemperor** [comment]
@Nhutruong96 em test lại thử xem. anh vừa tạo lại thử GCN cho đơn hàng em bị thì ko bị nữa.

**Comment by Nhutruong96** [comment]
đã fix xong
