### ISSUE TITLE
[Bug] Lỗi khi xem danh sách bảo hiểm xe máy

### ISSUE THREAD

**Issue by deathemperor** [papaya-insurtech/mango-bug-report#2]
https://sentry.io/organizations/papaya-li/issues/2779487083/?project=6034976&query=is%3Aunresolved

![image](https://user-images.githubusercontent.com/4255482/141240466-bb7a789f-ee10-43c3-bf89-3b3d5ca4e0ba.png)

**Comment by a8thunder** [comment]
DONE.
