### ISSUE TITLE
UAT release 15Nov - Thể hiện không rỏ phí vật chất xe - PTI

### ISSUE THREAD

**Issue by ToantranPPY** [papaya-insurtech/mango-bug-report#22]
Tại UI thông tin hợp đồng
- Phí BH vật chất xe: chỉ thể hiện phí vật chất cơ bản
![image](https://user-images.githubusercontent.com/94037218/141975065-5409c25b-4374-4e5e-a29d-cb43f685bf0d.png)

**Comment by deathemperor** [comment]
fixed on UAT

**Comment by ToantranPPY** [comment]
Testing okay
