### ISSUE TITLE
PRO/portal: không ghi nhận giấy chứng nhận bảo hiểm trên portal

### ISSUE THREAD

**Issue by ToantranPPY** [papaya-insurtech/mango-bug-report#23]
Không có giấy chứng nhận bảo hiểm trên portal
https://portal.pro.papaya.asia/portal/preorder-motorbike/291
https://portal.pro.papaya.asia/portal/preorder-motorbike/292
https://portal.pro.papaya.asia/portal/preorder-motorbike/293

**Comment by deathemperor** [comment]
fixed
