### ISSUE TITLE
[PRO-113] Deeplink

### ISSUE THREAD

**Issue by deathemperor** [papaya-insurtech/mango-bug-report#26]
- [x] Referral Deeplink
- [x] Deeplink khi click vào mở màn hình profile
- [x] Deeplink khi click vào mở từng màn hình order (order VCX, order Xe máy, order TNDS xe oto)

**Comment by a8thunder** [comment]
- [ ] Referral Deeplink
- [ ] Deeplink khi click vào mở màn hình profile
- [ ] Deeplink khi click vào mở từng màn hình order (order VCX, order Xe máy, order TNDS xe oto)
