### ISSUE TITLE
Firebase Remote Config

### ISSUE THREAD

**Issue by deathemperor** [papaya-insurtech/mango-bug-report#27]
https://firebase.google.com/docs/remote-config

- [ ] Cho phép tắt/mở 1 feature theo 1 hoặc nhiều user nào đó
- [ ] tắt/mở feature theo toàn bô user

**Comment by a8thunder** [comment]
- [ ]  Cho phép tắt/mở 1 feature theo 1 hoặc nhiều user nào đó
- [ ]  tắt/mở feature theo toàn bô user
