### ISSUE TITLE
PRO- thay đổi mã mapid đối với giao dich thanh toán qua CHAI-pay và VNPT epay

### ISSUE THREAD

**Issue by ToantranPPY** [papaya-insurtech/mango-bug-report#28]
Đề nghị thay đổi mã mapid đối với giao dich thanh toán qua CHAI-pay và VNPT epay, 
Ex; mapid: mango_prod_MOTORBIKE_171 =>mango_prod_MOTORBIKE_991267
(trong đó 991267 là mã đơn hàng)

**Comment by deathemperor** [comment]
done. em lên production phần này rồi nhe @ToantranPPY
