### ISSUE TITLE
PRO- Template báo giá xe thiếu đơn vị tính đối với BH Tai nạn

### ISSUE THREAD

**Issue by ToantranPPY** [papaya-insurtech/mango-bug-report#30]
PRO- Template báo giá xe hiện tại thiếu đơn vị đối với BH Tai nạn
(<Hạn mức> đ/chổ ngồi)
Figma: https://www.figma.com/file/AtS84moB2o5qRVsFPTyIKB/Digital-Broker?node-id=292%3A3490
![image](https://user-images.githubusercontent.com/94037218/142361718-dc18b6a6-384d-48c1-b6c5-7a158e11fc8b.png)

**Comment by deathemperor** [comment]
fixed
