### ISSUE TITLE
UAT: không có email thông báo nộp phí/ Nộp phí thành công cho KH

### ISSUE THREAD

**Issue by ToantranPPY** [papaya-insurtech/mango-bug-report#31]
UAT: không có email thông báo nộp phí/ Nộp phí thành công cho KH
http://papaya-mango-portal-uat.s3-website-ap-southeast-1.amazonaws.com/portal/tnds-car/f24175e9-66bb-4e31-ae1f-052a55294195
http://papaya-mango-portal-uat.s3-website-ap-southeast-1.amazonaws.com/portal/tnds-car/2e94f66a-6d0d-454c-9c86-b61481c5ed82

**Comment by deathemperor** [comment]
fixed
