### ISSUE TITLE
[Bug] The curator tool

### ISSUE THREAD

**Issue by duonglna** [papaya-insurtech/mango-bug-report#32]
- [x] Nút reset ở form không hoạt động
<img width="605" alt="create new model 2" src="https://user-images.githubusercontent.com/7956961/142400434-6e200af1-1d59-4347-aa31-453619e8038a.png">

- [x] Nên có search manufacturer  vì list khá nhiều, search để làm nhanh hơn
<img width="566" alt="create new model" src="https://user-images.githubusercontent.com/7956961/142400417-58e2efc7-bf58-4bcf-b4a8-fddfbb3b6c8b.png">

<img width="539" alt="mapping" src="https://user-images.githubusercontent.com/7956961/142404947-e497c1c8-bce3-4526-8b9d-f3d1a6f20142.png">
 
- [x] Mapping: có nên cho chọn 1 lần xong bấm lưu hoặc submit rồi yêu cầu user xác nhận 1 lần. Hiện nay mỗi lần tick phải xác nhận lại 1 lần
<img width="519" alt="mapping 2" src="https://user-images.githubusercontent.com/7956961/142405327-252ab2b6-c3cd-43c8-9a40-b17f3aeb0a15.png">

- [x] Mapping xong nên clear action đã chọn khi bấm Mapping trên 1 model khác: https://drive.google.com/file/d/1ABKVcnLNOVPo8_pa2gazAFcT4IAjax5G/view?usp=sharing

- [x] Search model ko ra kết quả (đang bị phân biệt hoa thường, kết quả search trả về ko ổn định
https://drive.google.com/file/d/1Kl_K7S9UjG1t8-63zh2UI2ReBokynEFA/view?usp=sharing

- [x] Nhập capacity ko lưu: https://drive.google.com/file/d/1hZ_ZKU77wljSU9XqaysXLwSmrj8P22GS/view?usp=sharing

- [x] Delete 1 manufacturer đang có gán với model: ko xóa được, nhưng vẫn thông báo đã xóa => câu thông báo nên clear hơn (vd: Bạn không thể xóa vì manufacturer này đang gán với các model
<img width="1158" alt="LoiDelete" src="https://user-images.githubusercontent.com/7956961/142406542-f1185e1d-ece9-4411-b050-29f73a9fc6ab.png">
)

- [x] Khi bấm tạo mới sau khi bấm edit 1 model xe nên clear input: https://drive.google.com/file/d/1XaK97tia5elZm79CsD5MUBqeDrL8KGTL/view?usp=sharing

**Comment by duonglna** [comment]
@deathemperor 

- [ ] Xóa Make bị lỗi

<img width="1229" alt="Screen Shot 2021-11-23 at 11 09 10 AM" src="https://user-images.githubusercontent.com/7956961/142970029-ebbf6c49-02ff-4d02-8647-374857f79c53.png">

- [ ] Search trong mapping form một số make hiện 2 kết quả dù chỉ có 1 make bên view Manufacturer / Make (vd Hyundai)

<img width="1161" alt="Screen Shot 2021-11-23 at 10 46 46 AM" src="https://user-images.githubusercontent.com/7956961/142970130-4a0319f3-1ccb-4de0-87fa-a14b610a0e58.png">

<img width="887" alt="Screen Shot 2021-11-23 at 10 47 13 AM" src="https://user-images.githubusercontent.com/7956961/142970137-3ea25cc2-f6c6-48a3-9ba9-deda1b2b5a18.png">

- [ ] Create model / make xong phải reload lại page mới hiện trong view hoặc chọn được Make trong box tạo Model.
- [ ] Form mapping bị lỗi hiển thị

<img width="927" alt="mapping_window" src="https://user-images.githubusercontent.com/7956961/142970443-cb768543-f7d0-4f83-b223-10bf9e1b9fb6.png">

**Comment by deathemperor** [comment]
riêng phần `Search trong mapping form một số make hiện 2 kết quả dù chỉ có 1 make bên view Manufacturer / Make (vd Hyundai)` thì phức tạp hơn 1 chút, giải thích:

Danh sách `Make` (menu `Vehicle Manufacturer`) là cách danh sách do Papaya tạo ra. Danh sách `Make` search khi map model là danh sách được crawl về. Vì khi crawl thì source data sẽ đa dạng, có thể họ đặt tên cho Make là Ford hoặc FORD hoặc fOrD, mình lấy về giữ y nguyên nên thành ra có 2 Makes trong list đó. các models thuộc Makes này là valid data, có thể dùng để map vào Papaya Model.

Có 1 giải pháp cho việc này đơn giản hơn là gộp data của 2 Makes này lại (của Ford và FORD) lại khi lấy về => cần edit các crawlers.
