### ISSUE TITLE
PRO- Portal không ghi nhận giấy chứng nhận bảo hiểm

### ISSUE THREAD

**Issue by ToantranPPY** [papaya-insurtech/mango-bug-report#34]
PRO- Portal không ghi nhận giấy chứng nhận bảo hiểm:
https://portal.pro.papaya.asia/portal/preorder-motorbike/314
https://portal.pro.papaya.asia/portal/preorder-motorbike/317
https://portal.pro.papaya.asia/portal/preorder-motorbike/318
https://portal.pro.papaya.asia/portal/preorder-motorbike/319

**Comment by deathemperor** [comment]
check log hệ thống không thấy PVI gọi gửi giấy chứng nhận cho hệ thống mình. hôm nay em sẽ liên lạc PVI để hỏi.

có 2 đơn thiếu TNNNTX dù thanh toán phí đó:
https://portal.pro.papaya.asia/portal/preorder-motorbike/318
https://portal.pro.papaya.asia/portal/preorder-motorbike/319

Em đã sửa luôn rồi. em sẽ cấp lại giấy nhé?

**Comment by deathemperor** [comment]
em đã xử lý xong tất cả trường hợp
