### ISSUE TITLE
PRO- đơn hàng TNDS xe máy của PTI không có giấy chứng nhận trên portal

### ISSUE THREAD

**Issue by ToantranPPY** [papaya-insurtech/mango-bug-report#36]
PRO- đơn hàng TNDS xe máy của PTI không có giấy chứng nhận trên portal: https://portal.pro.papaya.asia/portal/preorder-motorbike/302
Vui lòng check đã cấp đơn cho KH chưa

**Comment by deathemperor** [comment]
fixed. lý do là production API bị config sai lúc sửa config cho PVI
