### ISSUE TITLE
PROD- check địa chỉ trên giấy chứng nhận và portal chưa ghi nhận số GCN

### ISSUE THREAD

**Issue by ToantranPPY** [papaya-insurtech/mango-bug-report#45]
PROD- check địa chỉ trên giấy chứng nhận và portal chưa ghi nhận số GCN: https://portal.pro.papaya.asia/portal/tnds-car/42366514-87bb-4386-a238-39ce7e7a0495
![image](https://user-images.githubusercontent.com/94037218/143175304-c2606f31-c31c-4e33-974e-3f4d91d1e457.png)
![image](https://user-images.githubusercontent.com/94037218/143175380-187bd51d-0264-4cca-8eee-696e94005515.png)

**Comment by deathemperor** [comment]
Trường hợp này là do người dùng nhập thừa nha anh.
