### ISSUE TITLE
UAT- Test xe mới/ too; chụp hình trên mobile có có viền trắng dưới

### ISSUE THREAD

**Issue by ToantranPPY** [papaya-insurtech/mango-bug-report#49]
UAT- Test xe mới/ too; chụp hình trên mobile có có viền trắng dưới
![image](https://user-images.githubusercontent.com/94037218/143977982-8fe51322-2401-4eb4-8aa3-cdc1339a7fa2.png)

**Comment by a8thunder** [comment]
DONE!

**Comment by ToantranPPY** [comment]
Done
