### ISSUE TITLE
UAT- xe mới/ Năm sản xuất: giới hạn trong 3 năm so với hiện tại

### ISSUE THREAD

**Issue by ToantranPPY** [papaya-insurtech/mango-bug-report#50]
UAT- xe mới/ Năm sản xuất giới hạn trong 3 năm so với hiện tại

**Comment by a8thunder** [comment]
DONE!

**Comment by ToantranPPY** [comment]
done
![Screenshot_20211202-145822](https://user-images.githubusercontent.com/94037218/144381165-1d51a527-b28c-4dcd-a98d-37379f54cdf0.png)
