### ISSUE TITLE
UAT/ Xe mới: Chọn số chổ ngồi

### ISSUE THREAD

**Issue by ToantranPPY** [papaya-insurtech/mango-bug-report#51]
UAT/ Xe mới: Chọn số chổ ngồi: trong database 
- nếu dòng xe đã có số chổ ngồi thì hiện số chổ ngồi từ database
- Nếu dòng xe khách hàng input không có trong database thì cho KH chọn chổ ngồi

**Comment by a8thunder** [comment]
DONE!

**Comment by ToantranPPY** [comment]
Done
![Screenshot_20211202-150108](https://user-images.githubusercontent.com/94037218/144381706-0fffbc61-1fa3-4048-a2f1-4555801e9696.png)
![Screenshot_20211202-150116](https://user-images.githubusercontent.com/94037218/144381712-7bac18ea-bafc-4b26-9b95-ac05d72c8687.png)
