### ISSUE TITLE
Thêm deeplink: mở ra trang ký HĐĐT

### ISSUE THREAD

**Issue by deathemperor** [papaya-insurtech/mango-bug-report#52]
Ấn vào deeplink cần mở ra view này nếu user chưa ký HĐ. Nếu đã ký thì mở ra xem lại HĐ đã ký. Vì view ký HĐ này chỉ xem đc khi chưa ký.
![image](https://user-images.githubusercontent.com/4255482/143989593-64646d4b-52f9-4230-9516-eb81d13d7484.png)

**Comment by a8thunder** [comment]
DONE!

**Comment by deathemperor** [comment]
@a8thunder cho anh xin cái link

**Comment by deathemperor** [comment]
@LocPham0311 deeplink cho link ký HĐĐT nhấn từ email UAT: https://papaya-uat.onelink.me/RaTq/55432563

mỗi env có 1 link khác nhau nhe.
