### ISSUE TITLE
UAT/ Econtract: error khi nhập mã OTP

### ISSUE THREAD

**Issue by ToantranPPY** [papaya-insurtech/mango-bug-report#53]
UAT/ Econtract: error khi nhập mã OTP để ký hợp đồng điện tử
- iOS / SDT: 0345818682/ Mã CTV: 965661 
![Image from iOS](https://user-images.githubusercontent.com/94037218/144003108-a20118ae-0f05-42d7-8e27-aa547f33a8ea.png)

**Comment by deathemperor** [comment]
System ghi nhận được đây là lỗi của OnSign `{ error: -302, message: 'Phiên ký đang xử lý tài liệu' }`. Lỗi này thường xuyên bị khi tích hợp với họ. em đã raise lên thêm. Tình trạng hiện tại của lỗi này theo em đánh giá là khá nghiêm trọng, có thể sẽ ảnh hưởng việc release chức năng ký HĐĐT.

**Comment by deathemperor** [comment]
fixed trên bản UAT mới nhất

**Comment by ToantranPPY** [comment]
Đã ký được econtract
