### ISSUE TITLE
PROD/Sellers- không cập nhật được MST của CTV

### ISSUE THREAD

**Issue by ToantranPPY** [papaya-insurtech/mango-bug-report#54]
PROD/Sellers- không cập nhật được MST của CTV
https://portal.pro.papaya.asia/portal/sellers/detail/72
![image](https://user-images.githubusercontent.com/94037218/144168541-a692f354-e52b-4789-a4c5-b09e1def5680.png)

**Comment by LocPham0311** [comment]
fixed ròi anh lên test lại nhé @ToantranPPY

**Comment by ToantranPPY** [comment]
okay, done
