### ISSUE TITLE
UAT/ Xe mới: chon hãng xe, dòng xe, năm sx, click "Tiếp tục"button => không chuyển UI tiếp theo

### ISSUE THREAD

**Issue by ToantranPPY** [papaya-insurtech/mango-bug-report#55]
UAT/ Xe mới: chon hãng xe, dòng xe, năm sx, click "Tiếp tục"button => không chuyển UI tiếp theo
- Hãng xe: Toyota
- Dòng xe: Innova 2.0G
- Năm sx: 2020
- Ngày đăng ký: 1/12/2020
- Mục đích sd: không kinh doanh
=> click "tiếp tục" stuck tại màn hình này

**Comment by a8thunder** [comment]
DONE!

**Comment by deathemperor** [comment]
@ToantranPPY fixed trên bản UAT mới nhất rồi nhe anh

**Comment by ToantranPPY** [comment]
đã testing okay
