### ISSUE TITLE
PROD/ module TNDS oto: khi click "complete" button, portal báo lỗi không thực hiện được

### ISSUE THREAD

**Issue by ToantranPPY** [papaya-insurtech/mango-bug-report#56]
PROD/ module TNDS oto: khi click "complete" button, portal báo lỗi không thực hiện được
https://portal.pro.papaya.asia/portal/tnds-car/4f2870d3-766d-4260-a457-4b2b5901599c

**Comment by LocPham0311** [comment]
Đã fixed nha anh

**Comment by ToantranPPY** [comment]
Re testing okay
