### ISSUE TITLE
UAT/Xe mới: Giá trị xe trên app & bản chào giá khác nhau

### ISSUE THREAD

**Issue by ToantranPPY** [papaya-insurtech/mango-bug-report#60]
Mã đơn hàng: 889267
- Giá trị xe trên bản chào giá 1.000.000.000
- Giá trị xe trên app = 700.000.000

Mô tả thực hiện: 
1. UI chụp hình hóa đơn: chụp hình xe & ghi nhận giá trị xe 700.000.000, click "tiếp tục"
2. UI chọn quyền lợi: chọn full quyền lợi và điều khoản bổ sung, click tiếp tục
3. UI Báo phí, click nút back về UI chụp hình hóa đơn, điều chỉnh giá trị xe lên 1.000.000.0000 và thực hiện các bước chọn quyền lợi và lấy báo giá.

[BaoGia_Papaya_Pro_XeMới1.pdf](https://github.com/papaya-insurtech/mango-bug-report/files/7638116/BaoGia_Papaya_Pro_XeM.i1.pdf)

**Comment by deathemperor** [comment]
@a8thunder khi back lại & thay đổi giá trị xe, app ko ghi nhận lại vào order

**Comment by a8thunder** [comment]
DONE!

**Comment by deathemperor** [comment]
fixed trên build 4:00PM 2/12

**Comment by ToantranPPY** [comment]
okay
