### ISSUE TITLE
PROD/ module VCX: tại màn hình lấy báo giá bị lỗi

### ISSUE THREAD

**Issue by ToantranPPY** [papaya-insurtech/mango-bug-report#64]
PROD/ module VCX: tại màn hình lấy báo giá bị lỗi
![Image from iOS (1)](https://user-images.githubusercontent.com/94037218/144560090-8b707557-1838-4deb-bd77-479734b85f05.png)

**Comment by deathemperor** [comment]
Lỗi xảy ra khi chưa config thông tin commission. Em đã fix cho báo giá handle trường hợp chưa có thông tin commission.

Tuy nhiên CTV sẽ thấy commission = 0, mình cần set up thông tin này trên portal để giải quyết.

**Comment by ToantranPPY** [comment]
Đã setup comm
Đã có thấy báo giá
