### ISSUE TITLE
Handle trường hợp device ko có kết nối internet

### ISSUE THREAD

**Issue by deathemperor** [papaya-insurtech/mango-bug-report#65]
- Hiện thông báo không có kết nối internet
- Có nút retry
- Tự retry khi thấy có kết nối. Nếu có internet lại thì sẽ tắt thông báo

Related sentry issue: https://sentry.papaya.services/organizations/papaya-sentry/issues/42/?project=2&query=is%3Aunresolved

**Comment by a8thunder** [comment]
- [ ] home
- [ ] login
- [ ] insurance(car, motor, tnds)
- [ ] profile

**Comment by a8thunder** [comment]
DONE!

**Comment by ToantranPPY** [comment]
done
