### ISSUE TITLE
PRO-135: Export data đơn hàng đối soát với CTBH

### ISSUE THREAD

**Issue by ToantranPPY** [papaya-insurtech/mango-bug-report#66]
PRO-135: Export data đơn hàng đối soát với CTBH theo mẫu:
https://docs.google.com/spreadsheets/d/1bNU_S7dSKvwctToOXJX6GDDoA3m0NZT6x18-FapLQwY/edit#gid=0

**Comment by LocPham0311** [comment]
done

**Comment by ToantranPPY** [comment]
@LocPham0311 
- Thiếu biển kiểm soát -  ex: 056890
- Thiếu mã giấy chứng nhận - ex: 056890

**Comment by ToantranPPY** [comment]
- cho phép fillter theo CTBH

**Comment by ToantranPPY** [comment]
- Thiếu mã GCN - 730287

**Comment by ToantranPPY** [comment]
@LocPham0311 
- Đơn hàng 502131 thiếu giấy chứng nhận & biển số xe

**Comment by LocPham0311** [comment]
done

**Comment by ToantranPPY** [comment]
- ĐH 489032 xuất hiện 02 lần trong file đối soát
![image](https://user-images.githubusercontent.com/94037218/148915551-60ea728f-e9e8-4f73-922a-24010c4b4749.png)
- ĐH 115749, 817259, 016086 không có quyền lợi Tai nạn, nhưng trong file đối soát lại có
- ĐH 306064, 730287 . . .  chưa đúng về Hoa hồng DV và hoa hồng Đại Lý (số đúng: HHDV= 38.000,  HHDL = 18.000)

**Comment by deathemperor** [comment]
đã xong nha anh
