### ISSUE TITLE
PROD/ TNDS oto: thẻ complete thể hiện không đúng

### ISSUE THREAD

**Issue by ToantranPPY** [papaya-insurtech/mango-bug-report#67]
PROD/ TNDS oto: thẻ complete thể hiện không đúng
https://portal.pro.papaya.asia/portal/tnds-car
![image](https://user-images.githubusercontent.com/94037218/144779728-d300fddb-db38-47c7-ae69-a9da1c49afb1.png)

**Comment by deathemperor** [comment]
fixed on UAT

**Comment by ToantranPPY** [comment]
hi @deathemperor, anh raise bug trên prod mừ, check lại giúp anh

**Comment by deathemperor** [comment]
em mới fix trên UAT thôi anh. UAT cũng bị. khi nào ra bản mới thì portal sẽ đc deploy thì production sẽ đc fix.

**Comment by ToantranPPY** [comment]
Done
