### ISSUE TITLE
fix UI Health Care

### ISSUE THREAD

**Issue by a8thunder** [papaya-insurtech/mango-bug-report#68]
- [x] check lại ngày tháng năm sinh
- [x] padding bh tai nạn
- [x] disable thai sản(nam)
- [x] multiple select quotation(pdf)
- [ ] not selected 0 cần
- [x] auto fill người được mua bảo hiểm
- [x] show end date time
- [x] check format date time
- [x] add filter
- [x] remove other relationshop

**Comment by deathemperor** [comment]
@a8thunder bỏ option "khác" trong lựa chọn mối quan hệ
