### ISSUE TITLE
Bug Healthcare

### ISSUE THREAD

**Issue by duonglna** [papaya-insurtech/mango-bug-report#71]
- [x] [Webapp] Không scroll ở trang Trả lời câu hỏi trên desktop được (Desktop độ phân giải 1366 x 768)
- [x] [Webapp] Giao diện bị vỡ ở trang Trả lời câu hỏi trên điện thoại (iP X - Mở bằng Safari và Chrome), ko load được font chữ theo design
![z3017521475001_87c827a82a4c64e707bf2b30ffdd812c](https://user-images.githubusercontent.com/7956961/145753912-785b34ba-6c68-4661-9f4b-e38286d35742.jpg)
![z3017521478715_f4522a774fad003df8fa2e03e51a5dab](https://user-images.githubusercontent.com/7956961/145753923-38c44371-17ad-497f-9267-67874186e634.jpg)

- [x] [Webapp/App] Verify số CMND / CCCD: chỉ cho nhập dạng số, từ 9 - 12 kí tự (trên cả web app và app)
- [x] [App] Số tiền phí khác nhau ở trang Chi tiết đơn hàng và trang báo phí (của cùng 1 gói)
![z3017495858780_b15e7c16a940a8ac4e3b0a87cad8b376](https://user-images.githubusercontent.com/7956961/145754471-989a6432-acf2-408c-bb5b-4f30594a510e.jpg)
![z3017495867602_7aaba515f6d5bd8286df7ededd542514](https://user-images.githubusercontent.com/7956961/145754474-4a3ef619-dba2-4eb7-9ccb-09c687c5339e.jpg)

- [x] [App] Font chữ của Ngày sinh và Ngày bắt đầu bảo hiểm  đang khác font chữ design
![z3017495872516_7d8926443d698b8a75c85996d51324bd](https://user-images.githubusercontent.com/7956961/145755193-226257d6-61ad-42fd-aa8d-831f2071c923.jpg)
![z3017495904028_24c3838f6391f76417cf56b441a063bf](https://user-images.githubusercontent.com/7956961/145755198-bcc13533-29cf-4539-9a69-09b65539fa62.jpg)

- [x] [App] Sửa text "người yêu cầu BH" thành "người mua BH"
![z3017495883412_1f5428f0872a399e9b79244ffcfefdf4](https://user-images.githubusercontent.com/7956961/145755406-526598d7-9a42-468b-b338-e9ed9a2258f1.jpg)

- [x] [App] Ngày bắt đầu bảo hiểm: không cho phép chọn ngày quá khứ
- [x] [App] Style lại Disable checkbox (đang để màu hồng, đổi thành màu xám)
- [x] Đổi tên phần màu xanh khoanh bằng đoạn bên dưới "Papaya sẽ gửi yêu cầu bảo hiểm và câu hỏi sức khỏe đến khách hàng qua email của người mua bảo hiểm để xác nhận thông tin."
![z3017495873869_e733b73b120b2d55695a84f7d96fea36](https://user-images.githubusercontent.com/7956961/145755981-cb49fab5-68f1-4e84-990b-f879632577f7.jpg)

- [x] Báo lỗi khi chưa chọn gói và bấm Lấy phí
![z3017598225781_b5a144fe61106711ec2af5373d17ee89](https://user-images.githubusercontent.com/7956961/145756517-a48eccf8-f1b0-417d-9d50-94462c8faed1.jpg)

- [x] [App] Cách tính tuổi đang bị sai (phải tính tới ngày sinh nhật gần nhất): Vd người được bảo hiểm sinh ngày 15/12/2016, ngày bắt đầu bảo hiểm là 13/12/2021 => tuổi bảo hiểm của người này là 4 tuổi, chưa được bảo hiểm nhưng trên app vẫn cho mua

**Comment by duonglna** [comment]
- [ ] [App] Các field chọn ngày: khi đã chọn ngày, sau đó bấm chọn lại vào field nên load đến thời điểm của ngày đã chọn (hiện nay đang load đến ngày hiện tại

https://user-images.githubusercontent.com/7956961/145783255-297f2f16-d7b9-4de4-bf01-95551b4b893f.mp4

- [ ] [App] UI lúc hiển thị gói khoảng cách giữa các gói khác design
![z3018280910079_69166044fe84d2ed25cd5d27e9e4f3b0](https://user-images.githubusercontent.com/7956961/145783224-6bb52d39-7250-465f-930c-b6bca44e3295.jpg)

**Comment by a8thunder** [comment]
DONE!
