### ISSUE TITLE
UAT 13Dec21 - Web App

### ISSUE THREAD

**Issue by nhinguyenpapaya** [papaya-insurtech/mango-bug-report#72]
- [x] Chỉ hiện bàn phím số khi điền OTP
https://user-images.githubusercontent.com/96039997/145806956-24388926-2249-4694-9e51-fb1a1a335885.mp4
- [x] Sửa UI Người được bảo hiểm khi NĐBH cũng là người mua BH
- [x] Không cho chỉnh sửa thông tin khi NĐBH cũng là người mua BH
- [x] Field địa chỉ lấy đủ cả địa chỉ, phường, quận, tỉnh/tp
![1639395659714](https://user-images.githubusercontent.com/96039997/145806735-814728b9-2cd5-4bb1-a853-75a723d95e82.jpg)

**Comment by nhinguyenpapaya** [comment]
- [ ] add background cho các sticky button
![image](https://user-images.githubusercontent.com/96039997/145935394-d5bfefe2-deb0-4ab4-ba5a-be38e1336a39.png)

**Comment by nhinguyenpapaya** [comment]
- [ ] Thời hạn bảo hiểm: từ đến bị ngược 
![1639472799050](https://user-images.githubusercontent.com/96039997/145967956-6f39923f-fb7a-4953-930a-4f71390fba27.jpg)

- [ ] Câu hỏi sức khoẻ PVI, trong vòng 3 năm... 
Mặc định là không chọn giá trị nào, để người trả lời tự chọn "có/không" 
![1639472799045](https://user-images.githubusercontent.com/96039997/145968234-8d34d323-6a72-4af8-8629-d283c467a3a9.jpg)

**Trang Hoàn tất/Từ chối yêu cầu bảo hiểm:**

- [ ] Khi đã bấm "Hoàn tất" và sang màn hình cuối, nếu user bấm nút back trên trình duyệt, sẽ cho load lại trang Hoàn tất/Từ chối - không cho trở về phần trả lời câu hỏi
- [ ] Khi đã bấm "Hoàn tất" và sang màn hình cuối, nếu user bấm reload lại trang, sẽ hiện lại trang Hoàn tất/Từ chối
![image-2](https://user-images.githubusercontent.com/96039997/145968896-05394e80-ab2c-4776-833f-2a99fac9f378.png)
- [ ] Cho phép copy text ở trang này hoặc cho copy số tài khoản, tên người thụ hưởng
- [ ] Thay đổi UI cho nút Thanh toán trực tuyến và thông tin chuyển khoản
![image](https://user-images.githubusercontent.com/96039997/145968844-a28eb87a-d29d-49df-a007-d387c8b03a1f.png)

**Comment by nhinguyenpapaya** [comment]
- [ ] Nhập OTP lần 1 sai. Nhập OTP lần 2 đúng nhưng vẫn báo sai OTP
https://user-images.githubusercontent.com/96039997/145983414-9d7e1c4d-2c9a-4372-9564-bd06a8e8ab19.mp4
- [ ] Không cập nhật được thông tin người được bảo hiểm và người mua bảo hiểm ở web app
![z3021364083269_751de205914284836520e5a47deb98cd](https://user-images.githubusercontent.com/96039997/145983526-43f962f6-10c4-4f98-90d7-d683a9f5eff8.jpg)
- [ ] Ở trang xác nhận đang không click đọc được thông tin Nguyên tắc bảo hiểm do nút đang bị che - iphone X
- [ ] Nếu bấm nút back trên trình duyệt thì khi về trang Thông tin gói bảo hiểm sẽ không hiển thị được phí của từng quyền lợi
![webappgoibaohiem](https://user-images.githubusercontent.com/96039997/145984007-cb1c174f-931a-4692-908e-aa9563e35298.jpg)
- [ ] Cho hiện Mối quan hệ theo thứ tự và chính tả là Cha / Mẹ / Chồng / Vợ / Con
- [ ] Sửa tên các gói bảo hiểm theo danh sách: Tai nạn cá nhân, Điều trị Nội trú, Điều trị Ngoại trú, Chăm sóc răng, Thai sản
![image](https://user-images.githubusercontent.com/96039997/145984538-13f908ee-dfe3-448f-92e8-7d25db293c9e.png)

**Comment by LocPham0311** [comment]
add background cho các sticky button -> chưa làm IU cho desktop

**Comment by nhinguyenpapaya** [comment]
- [ ] Câu hỏi sức khoẻ PVI_2
Lúc đầu trả lời "Có", quay lại sửa thành "Không" thì trang xác nhận vẫn hiện là "Có"
https://user-images.githubusercontent.com/96039997/146524905-6f653e9a-d543-478e-8877-95e231be8056.mp4

- [ ] Câu hỏi sức khoẻ PVI_1
Trả lời có -> đến trang xác nhận -> bấm back trên form -> hiện ra trang câu hỏi sức khoẻ PVI 3
https://user-images.githubusercontent.com/96039997/146524931-f5110329-9086-47b3-b070-56f323cd9910.mp4

**Comment by duonglna** [comment]
@LocPham0311  có time quay lại chặn chỗ này nha em
 Khi đã bấm "Hoàn tất" và sang màn hình cuối, nếu user bấm nút back trên trình duyệt, sẽ cho load lại trang Hoàn tất/Từ chối - không cho trở về phần trả lời câu hỏi
