### ISSUE TITLE
UAT 13Dec21 - Mobile App

### ISSUE THREAD

**Issue by nhinguyenpapaya** [papaya-insurtech/mango-bug-report#73]
- [x] Ngày tháng năm sinh UI field:
+ cho màu chữ đen trong text box
+ size text box bằng các text box khác
- [x] Đổi Placeholder field Họ tên: "Tên người nhận" -> "Tên người được BH"
![1639396522166](https://user-images.githubusercontent.com/96039997/145808230-ab810eb8-bac1-4643-a0b0-a66165c1794b.jpg)
- [x] Đổi Title Mối quan hệ với người mua BH: "Hình thức" -> "Mối quan hệ"
![1639396522182](https://user-images.githubusercontent.com/96039997/145808492-62061d3c-223e-4295-963c-0b5b632a3c8d.jpg)

**Comment by a8thunder** [comment]
DONE!
