### ISSUE TITLE
UAT/BHSK - Quyền lợi Tai nạn thể hiện số âm

### ISSUE THREAD

**Issue by ToantranPPY** [papaya-insurtech/mango-bug-report#74]
UAT/BHSK - Quyền lợi Tai nạn thể hiện số âm
![image](https://user-images.githubusercontent.com/94037218/145955087-ef18fb61-8a2f-40ad-a19d-edbc3b5b5507.png)

**Comment by a8thunder** [comment]
DONE!

**Comment by ToantranPPY** [comment]
Done
