### ISSUE TITLE
UAT/BHSK - UI nhập OTP chuyển bàn phím số

### ISSUE THREAD

**Issue by ToantranPPY** [papaya-insurtech/mango-bug-report#75]
UAT/BHSK - UI nhập OTP chuyển bàn phím số
![image](https://user-images.githubusercontent.com/94037218/145955439-884de7eb-294e-4db4-8e09-f1bbfce2148b.png)

**Comment by deathemperor** [comment]
đã xong

**Comment by ToantranPPY** [comment]
Done
