### ISSUE TITLE
UAT/BHSK - Link thanh toán không click được

### ISSUE THREAD

**Issue by ToantranPPY** [papaya-insurtech/mango-bug-report#76]
1. Edit Thanh toán trực tiếp -> Thanh toán trực tuyến
2. Redirect khi click vào "THANH TOÁN TRỰC TUYẾN"
![image](https://user-images.githubusercontent.com/94037218/145955768-f3215b92-bcdf-426d-9ef1-2e72c2751d5a.png)

**Comment by deathemperor** [comment]
đã fixed

**Comment by ToantranPPY** [comment]
Done
