### ISSUE TITLE
UAT/BHSK - Portal

### ISSUE THREAD

**Issue by ToantranPPY** [papaya-insurtech/mango-bug-report#77]
- [x] Thêm link trả lời câu hỏi sức khỏe trên webapp
- [x] Thể hiện phí bảo hiểm cho từng quyền lợi bảo hiểm
- [x] Chức năng export file pdf đơn yêu cầu BH theo mẫu công ty bảo hiểm
- [x] Button chuyển trạng thái đơn hàng: Complete/Decline

**Comment by deathemperor** [comment]
done

**Comment by ToantranPPY** [comment]
@deathemperor , okay rồi Lộc, deloy prod giúp anh
