### ISSUE TITLE
UAT 14Dec21 - Mobile

### ISSUE THREAD

**Issue by nhinguyenpapaya** [papaya-insurtech/mango-bug-report#78]
- [x] Tạo đơn PVI chưa có bước chọn nghề nghiệp
![image](https://user-images.githubusercontent.com/96039997/145977982-7ef2d2e1-85fd-4643-bdbc-b13361d151ae.png)

- [x] Cho nhập tự do số, chữ,... ở field Số CCCD/CMND/Giấy khai sinh của Người được bảo hiểm
- [x] Đổi label "Mối quan hệ với người yêu cầu BH" -> "Mối quan hệ với người mua BH"
![image](https://user-images.githubusercontent.com/96039997/145978378-0350dd74-caa0-4f0b-bf73-8767ecff9c15.png)

- [x] #85
- [x] #86
![image](https://user-images.githubusercontent.com/96039997/145979246-90fc6979-c25b-44d0-8250-18fa320fdc93.png)
![image](https://user-images.githubusercontent.com/96039997/145979657-85f50337-2ec5-449b-a4d6-41c44a2140a9.png)
![image](https://user-images.githubusercontent.com/96039997/145980277-f8fc3a05-5342-49b2-b7f9-dff9d2689a54.png)
![image](https://user-images.githubusercontent.com/96039997/145980532-159c43fc-3329-4349-adcf-38ae9e015313.png)
![image](https://user-images.githubusercontent.com/96039997/145980669-cf486d3d-d021-494b-8ed2-54a12be6c806.png)

- [x] Thể hiện tình trạng "Đã tính phí"
![Screenshot_2021-12-14-17-28-47-347_asia papaya pro uat](https://user-images.githubusercontent.com/96039997/145981531-b2b051cb-cec4-43b5-b3ce-9a7d2f1a5217.jpg)

- [x] Cho thêm nút "Tạo đơn" ở giao dịch khi tình trạng là "Đã tính phí", "Đã lấy file báo giá" - bấm vào ra trang báo phí
![image](https://user-images.githubusercontent.com/96039997/145981804-b7c07356-e59e-443b-a477-6a087048dccf.png)

**Comment by a8thunder** [comment]
DONE!
