### ISSUE TITLE
PROD/ cc email cho CTV đối với liên quan đến đơn hàng

### ISSUE THREAD

**Issue by ToantranPPY** [papaya-insurtech/mango-bug-report#79]
Đối với những email:
- thông báo về đóng phí / chụp hình
- thông báo xác nhận đóng phí
- thông báo phát hành giấy chứng nhận bảo hiểm
- khác ( liên quan đến đơn hàng)
Cần add cc email của CTV

**Comment by deathemperor** [comment]
done UAT

**Comment by ToantranPPY** [comment]
UAT okay, deloy product giúp anh. tks
