### ISSUE TITLE
UAT / Healthcare - [Webapp] Không nhập liệu trả lời câu hỏi PVI được

### ISSUE THREAD

**Issue by duonglna** [papaya-insurtech/mango-bug-report#80]
Device: iPhone X, Browser: Safari

- [x] Không nhập liệu ở ô Lý do được
- [x] Không chọn ngày tháng ở ô Ngày

![image](https://user-images.githubusercontent.com/7956961/146117123-4686d0f4-dc26-4f53-9873-cc91b056c6e9.png)
![image](https://user-images.githubusercontent.com/7956961/146117129-af2c470e-5d82-49b0-b494-878b8151fbb2.png)

**Comment by nhinguyenpapaya** [comment]
- [ ] chưa có chỗ upload bản sao xét nghiệm
![1639652933614](https://user-images.githubusercontent.com/96039997/146361332-12a595d6-0b63-4e8d-8857-829980e3d747.jpg)
