### ISSUE TITLE
UAT/Heathcare: UI trả lời nhóm ngành PVI không rỏ - Android 

### ISSUE THREAD

**Issue by ToantranPPY** [papaya-insurtech/mango-bug-report#81]
UAT/Heathcare: UI trả lời nhóm ngành PVI không rỏ - Android 
![image](https://user-images.githubusercontent.com/94037218/146299634-eeee71ff-b139-4e0d-bf94-6d7f3dca8140.png)

**Comment by a8thunder** [comment]
DONE!

**Comment by ToantranPPY** [comment]
done
