### ISSUE TITLE
UAT/Heathcare: UI thông báo từ chối do nhóm ngành của PVI

### ISSUE THREAD

**Issue by ToantranPPY** [papaya-insurtech/mango-bug-report#82]
UAT/Heathcare: UI thông báo từ chối do nhóm ngành của PVI, 
"Chọn bảo hiểm khác" chưa chuyển redirect
![image](https://user-images.githubusercontent.com/94037218/146300108-f0d2b58f-9d29-499d-b82c-46924e089f18.png)

**Comment by a8thunder** [comment]
DONE!

**Comment by ToantranPPY** [comment]
Done
