### ISSUE TITLE
UAT/Heathcare: UI thông tin thanh toán, thế hiện phí Tai nạn < 0

### ISSUE THREAD

**Issue by ToantranPPY** [papaya-insurtech/mango-bug-report#83]
UAT/Heathcare: UI thông tin thanh toán, 
- Thế hiện phí Tai nạn < 0
- Thể hiện phí BH sai

![image](https://user-images.githubusercontent.com/94037218/146300857-7a88bb54-88e5-4faf-91fe-0107fd5b32d0.png)

**Comment by duonglna** [comment]
@a8thunder  khi xem Chi tiết đơn hàng từ tab Giao dịch, phần title đang dùng là Thông tin thanh toán => Sửa lại thành "Thông tin đơn hàng" như trong design luôn nha

![image](https://user-images.githubusercontent.com/7956961/146307596-288723a9-1a29-4c8f-b2d0-f3cba9a1ffe9.png)

**Comment by a8thunder** [comment]
DONE!

**Comment by ToantranPPY** [comment]
Hi @a8thunder , re-check phần thể hiện phí chưa đúng ở UI Thông tin thanh toán:
Dơn hàng: http://papaya-mango-portal-uat.s3-website-ap-southeast-1.amazonaws.com/portal/health-care-orders/861bc6a3-a9b7-4922-ad26-d0515a2cba79
![image](https://user-images.githubusercontent.com/94037218/146486802-5d57de03-ad37-4cf5-aaa0-5d733d5d0e2a.png)

**Comment by ToantranPPY** [comment]
done
