### ISSUE TITLE
UAT/Heathcare: thời hạn bảo hiểm 

### ISSUE THREAD

**Issue by ToantranPPY** [papaya-insurtech/mango-bug-report#87]
Hiệu lực BH đang dư 1 ngày 
Đúng: hiệu lực bảo hiểm 12 tháng thì 27/08/2021 đến 26/08/2022
![image](https://user-images.githubusercontent.com/94037218/146489318-818bc5f3-5b0d-4a76-9630-c191900d330c.png)

**Comment by duonglna** [comment]
Cái này sửa cho cả bên webapp / portal / các template luôn đúng ko anh @ToantranPPY

**Comment by ToantranPPY** [comment]
hi @duonglna , đúng rồi em

**Comment by a8thunder** [comment]
DONE!

**Comment by ToantranPPY** [comment]
![image](https://user-images.githubusercontent.com/94037218/146706336-9cca097b-3622-4aa6-b8f9-d870ba0af345.png)
thời hạn bảo hiểm SK tính theo ngày; không tính theo giờ

**Comment by deathemperor** [comment]
fixed

**Comment by ToantranPPY** [comment]
done
