### ISSUE TITLE
UAT/Heathcare: format về ngày sinh của NĐBH

### ISSUE THREAD

**Issue by ToantranPPY** [papaya-insurtech/mango-bug-report#88]
Điều chỉnh format ngày sinh NĐBH "dd/mm/yyyy"
![image](https://user-images.githubusercontent.com/94037218/146489509-edca1b60-3e1f-4679-8439-51972b104bb6.png)

**Comment by a8thunder** [comment]
DONE!

**Comment by ToantranPPY** [comment]
done
