### ISSUE TITLE
UAT/Heathcare: Giới tính = Nam, nhưng vẫn ghi nhận Quyền lợi thai sản

### ISSUE THREAD

**Issue by ToantranPPY** [papaya-insurtech/mango-bug-report#89]
DH này NĐBH (F) nhưng vẫn ghi nhận quyền lợi thai sản
http://papaya-mango-portal-uat.s3-website-ap-southeast-1.amazonaws.com/portal/health-care-orders/8c085d5d-45db-46cd-ada4-f8bc6cfac4b9
Chưa reproduce được
![image](https://user-images.githubusercontent.com/94037218/146703903-2e6edaf3-6171-495e-975b-0d09355c4a9e.png)

**Comment by ToantranPPY** [comment]
trình tự case này như sau:
1- Khai báo NĐBH (M)
2- Bước tạo đơn chọn NĐBH >< CHĐ
3-Check thông tin LA là (F)
http://papaya-mango-portal-uat.s3-website-ap-southeast-1.amazonaws.com/portal/health-care-orders/e4c4c1e1-2d64-4b46-8d9f-b32eb2d3fdac

**Comment by deathemperor** [comment]
em không tái tạo lại được theo như hướng dẫn của anh

**Comment by deathemperor** [comment]
cùng lỗi với https://github.com/papaya-insurtech/mango-bug-report/issues/90
