### ISSUE TITLE
UAT/Healthcare - [App] Đơn hàng tạo từ mục Giao dịch, giới tính auto thành Nam

### ISSUE THREAD

**Issue by duonglna** [papaya-insurtech/mango-bug-report#90]
B1: Tạo 1 ĐH sức khỏe với giới tính Nữ
B2: Đến bước Tính phí hoặc Lấy báo phí thoát ra không tiếp tục
B3: Vào mục Giao dịch, chọn BHSK, chọn Tạo đơn cho ĐH ở bước 2 => phần Giới tính ngươi được bảo hiểm lúc nào cũng là Nam

=> Giới tính cần giữ nguyên giá trị như đã chọn trước đó

![image](https://user-images.githubusercontent.com/7956961/146869958-a209ef96-201c-4274-980d-594a523bf05c.png)

**Comment by a8thunder** [comment]
DONE!
