### ISSUE TITLE
UAT [App] "Lưu ảnh" trong chi tiết 1 đơn hàng

### ISSUE THREAD

**Issue by duonglna** [papaya-insurtech/mango-bug-report#92]
Nút "Lưu ảnh" trong chi tiết 1 ĐH bất kì (cả SK, VCX, TNDS) từ menu Giao dịch: bấm vào báo "Có lỗi xảy ra"

![image](https://user-images.githubusercontent.com/7956961/146892479-1b2f2041-2c63-4fc3-bf38-1dbdd82f7997.png)

**Comment by duonglna** [comment]
@a8thunder  tạo đơn hàng mới xong đến bước Xem chi tiết Thông tin thanh toán bấm Lưu ảnh (của ô tô) cũng bị lỗi ko Lưu được nhe

**Comment by a8thunder** [comment]
DONE!

**Comment by duonglna** [comment]
@a8thunder : Mua VCX, nếu save từ Giao dịch thì OK nhưng vừa mua xong save ảnh thì loading: https://share.icloud.com/photos/07aQ8UMTqnoEQfWzU0ZLalp2Q
