### ISSUE TITLE
UAT / Vật chất xe : Bỏ chọn Vật chất xe ở bước chọn Phạm vi bảo hiểm thì bị lỗi không tạo đơn hàng

### ISSUE THREAD

**Issue by duonglna** [papaya-insurtech/mango-bug-report#93]
1. Ở bước chọn Gói bảo hiểm: Chọn VCX + TNDS
![image](https://user-images.githubusercontent.com/7956961/147030846-a776f25d-467c-4f87-96ff-0a9342c15be1.png)

2. Sau đó khi tạo đơn ở bước Phạm vi bảo hiểm bỏ chọn VCX
![image](https://user-images.githubusercontent.com/7956961/147030897-e0177402-2e89-4f20-9dcd-20b1dfee7ba2.png)

3. Tạo đơn báo lỗi Error during communication
![image](https://user-images.githubusercontent.com/7956961/147030907-8d27fbb3-adb7-4ccb-92d8-3569b2ce03c9.png)

**Comment by deathemperor** [comment]
fixed
