### ISSUE TITLE
UAT/Healthcare: Email hiển thị không đúng số tiền ở các dòng quyền lợi

### ISSUE THREAD

**Issue by duonglna** [papaya-insurtech/mango-bug-report#94]
Ở các dòng quyền lợi đang hiển thị số random (123).
Không chọn quyền lợi mở rộng nhưng ở email vẫn có dòng Quyền lợi mở rộng
![image](https://user-images.githubusercontent.com/7956961/147075901-3d9cf576-02ae-482e-a043-8dc628f64060.png)

**Comment by deathemperor** [comment]
fixed on UAT
