### ISSUE TITLE
UAT/Healthcare - 22Dec21 - File báo giá

### ISSUE THREAD

**Issue by nhinguyenpapaya** [papaya-insurtech/mango-bug-report#95]
- [x] Không chọn quyền lợi, đổi text "Miễn phí" -> "Không tham gia"
![1640172185140](https://user-images.githubusercontent.com/96039997/147086695-88f69142-f3de-43aa-8bd3-0b5f28f691f7.jpg)

**Comment by nhinguyenpapaya** [comment]
- [ ] Báo phí thiếu "Tai nạn cá nhân"
Bỏ "Tai nạn cá nhân" khi chọn gói -> tick chọn "Thêm BH tai nạn cá nhân" khi lấy báo phí
https://user-images.githubusercontent.com/96039997/147181957-a26f8eb6-92fb-4832-a7ef-a5c31506e28b.mp4
- [ ] Báo phí thiếu "Điều trị nội trú" & Phí của PVI hiện "Miễn phí"
Bỏ "Điều trị nội trú" khi chọn gói -> tick chọn "Thêm điều trị nội trú" khi lấy báo phí
https://user-images.githubusercontent.com/96039997/147182018-a19ed023-8ad3-441f-94d6-731764e0e91b.mp4

**Comment by duonglna** [comment]
Update 2 chỗ nhỏ về câu chữ trên bảng Báo phí 
1. Sửa thành hyperlink đến https://www.pvicare.vn/data/main/DS_BVBL.PDF
2. Sửa dòng "TẠI CÁC BỆNH VIỆN CÓ BẢO LÃNH VIỆN PHÍ" chỗ số (2) thành "TẠI CÁC BỆNH VIỆN/CƠ SỞ Y TẾ NGOÀI DANH SÁCH BẢO LÃNH VIỆN PHÍ"
![z3058165516343_1c467d5f039319d7554756a012a65461](https://user-images.githubusercontent.com/7956961/147450344-eceee399-ff15-4869-89c0-e906d95c3546.jpg)

**Comment by nhinguyenpapaya** [comment]
> Update 2 chỗ nhỏ về câu chữ trên bảng Báo phí
> 
> 1. Sửa thành hyperlink đến https://www.pvicare.vn/data/main/DS_BVBL.PDF
> 2. Sửa dòng "TẠI CÁC BỆNH VIỆN CÓ BẢO LÃNH VIỆN PHÍ" chỗ số (2) thành "TẠI CÁC BỆNH VIỆN/CƠ SỞ Y TẾ NGOÀI DANH SÁCH BẢO LÃNH VIỆN PHÍ"
> 
> ![z3058165516343_1c467d5f039319d7554756a012a65461](https://user-images.githubusercontent.com/7956961/147450558-26aae7ea-94df-4cff-9e48-379b9b32c09d.jpg)

@LocPham0311 em update 2 cái này nữa nha

**Comment by LocPham0311** [comment]
done
