### ISSUE TITLE
UAT 22Dec21 - Web app

### ISSUE THREAD

**Issue by nhinguyenpapaya** [papaya-insurtech/mango-bug-report#96]
- [x] Không cho chỉnh sửa số điện thoại của người mua bảo hiểm
![image](https://user-images.githubusercontent.com/96039997/147087337-d94f25a8-72da-4d9f-9b74-58f339aa72fc.png)
- [x] Không hiện đầy đủ quyền lợi ngoại trú và chăm sóc răng của PTI
![1640172185123](https://user-images.githubusercontent.com/96039997/147087427-74b86e6d-1b22-4be7-988d-4821cec2cbc3.jpg)
- [x] In hoa các quyền lợi chính "Tai nạn cá nhân" -> TAI NẠN CÁ NHÂN
![1640172185123](https://user-images.githubusercontent.com/96039997/147087587-eba298ae-8e55-4e37-8117-ed054839a01c.jpg)

**Comment by LocPham0311** [comment]
Không hiện đầy đủ quyền lợi ngoại trú và chăm sóc răng của PTI -> check lại team ops đã input đủ quyền lợi chưa

**Comment by nhinguyenpapaya** [comment]
- [ ] Chỉ cho nhập số khi chỉnh sửa CMND/CCCD của người mua bảo hiểm

**Comment by LocPham0311** [comment]
fixed
