### ISSUE TITLE
UAT/Healthcare: Giấy Yêu cầu bảo hiểm

### ISSUE THREAD

**Issue by duonglna** [papaya-insurtech/mango-bug-report#97]
Trường hợp Người được bảo hiểm cũng là Người yêu cầu bảo hiểm, phần Quan hệ với NYCBH hiện chữ "Bản thân"

![image](https://user-images.githubusercontent.com/7956961/147182916-f8caa6e8-b11f-47a7-b401-8a8145d12b28.png)

**Comment by deathemperor** [comment]
đã apply

**Comment by duonglna** [comment]
@deathemperor :
Case PVI, em trả lời câu "Trong vòng 3 năm qua hoặc bây giờ,Ông/Bà đang được bác sỹ theo dõi sức khỏe hoặc đang được điều trị y tế (ngoại trú hay nội trú)?" chọn **Không** nhưng Giấy yêu cầu BH ghi nhận **Có**

![image](https://user-images.githubusercontent.com/7956961/147201482-543cf0d9-83bc-4105-94c5-aed136bcbe7f.png)
![image](https://user-images.githubusercontent.com/7956961/147201668-ddc7ade0-9665-4ffa-8d52-1e38020b8805.png)

**Comment by duonglna** [comment]
Trường hợp Nam ko trả lời câu hỏi sinh sản nhưng vẫn hiện ở giấy YCBH => cần ẩn đi

![image](https://user-images.githubusercontent.com/7956961/147205806-54196770-c7ab-4453-a609-e6855b26ff01.png)

**Comment by deathemperor** [comment]
@duonglna anh đã apply các thay đổi
