### ISSUE TITLE
UAT/BHSK/Email thông tin đơn hàng; Sai thời hạn BH & chưa cc email CTV

### ISSUE THREAD

**Issue by ToantranPPY** [papaya-insurtech/mango-bug-report#98]
- Email thông tin đơn hàng sai thời hạn bảo hiểm
- Email thông tin đơn hàng chưa cc email CTV
![image](https://user-images.githubusercontent.com/94037218/147205463-fdf23cd8-e9cf-4f2e-b08e-df2e8ea58995.png)

**Comment by deathemperor** [comment]
fixed on UAT

**Comment by ToantranPPY** [comment]
Done
